builders:
  flutter_xrouter_builder:
    import: "package:flutter_xrouter_compiler/library_builder.dart"
    builder_factories: ['routeBuilder']
    build_extensions: { '.dart': ['.g.dart'] }
    required_inputs: ['.dart']
    auto_apply: root_package
    build_to: source